name: Run Booking Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'   # run every 10 minutes

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install undetected-chromedriver

      - name: Run bot (headless)
        run: |
          python boot.py --headless

      - name: Send email notification
        if: failure()   # only if boot.py exits with error
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: "alaztn25@gmail.com"
          password: "alazie4646"
          subject: "🚀 Appointment Page Opened!"
          to: "alaztn45@gmail.com"
          from: "Booking Bot <alaztn25@gmail.com>"
          body: "The bot just detected that the appointment page is OPEN!"
