name: Run Bot

on:
  workflow_dispatch:   # only run when you trigger manually

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Bot
        run: |
          python boot.py
