name: Run Booking Bot (matrix attempts)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  booking:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        attempt: [1,2,3,4,5]   # adjust attempts count
      max-parallel: 1         # sequential: each attempt runs on a fresh VM

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install

      - name: Run bot on this VM (will keep trying up to MAX_RUN_MINUTES)
        id: runbot
        continue-on-error: true
        run: |
          echo "Starting attempt #${{ matrix.attempt }} on fresh VM..."
          # adjust MAX_RUN_MINUTES here if you want; default passed is 20
          python boot.py --headless --max-minutes 20
          CODE=$?
          echo "bot_exit_code=$CODE" >> $GITHUB_OUTPUT

      - name: If success -> cancel rest of workflow (stop other matrix jobs)
        if: steps.runbot.outputs.bot_exit_code == '0'
        run: |
          echo "Appointment reached on attempt #${{ matrix.attempt }} — cancelling remaining jobs..."
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"

      - name: Log reason for next attempt
        if: steps.runbot.outputs.bot_exit_code != '0'
        run: |
          echo "Attempt #${{ matrix.attempt }} finished with code ${{ steps.runbot.outputs.bot_exit_code }}. Next matrix attempt (fresh VM) will run if available."
