name: Run Booking Bot

on:
  workflow_dispatch:

jobs:
  booking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        attempt: [1, 2, 3, 4, 5]   # number of fresh-VM attempts
      max-parallel: 1             # IMPORTANT: run sequentially, not parallel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install webdriver-manager selenium

      - name: Run booking bot
        id: run-bot
        run: |
          echo "➡️ Starting attempt ${{ matrix.attempt }}"
          python boot.py --headless || echo "exit_code=$?" >> $GITHUB_ENV

      - name: Check result
        if: always()
        run: |
          code="${{ env.exit_code }}"
          echo "Exit code was: $code"

          if [ "$code" = "0" ]; then
            echo "✅ Success! Stopping workflow."
            exit 0
          elif [ "$code" = "2" ]; then
            echo "⚠️ IP blocked. Moving to next VM..."
            exit 0   # mark as success so next matrix attempt runs
          else
            echo "❌ Unexpected exit (shouldn’t happen because boot.py retries internally)."
            exit 1
          fi
